openapi: 3.0.0
info:
  title: Qanapi API v2
  version: 2.0.0
  description: Qanapi API version 2
servers:
  - url: https://{subdomain}.qanapi.cloud/api/v2
    description: The Qanapi API server
    variables: {
      "subdomain": {
        "default": "",
        "description": "Customer-specific subdomain."
      },
    }
paths:
  "/encrypt":
    post:
      summary: "Encrypt data"
      operationId: "postV2Encrypt"
      x-mint: "/api/v2/encrypt"
      responses:
        '200':
          description: "Encrypted data"
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
  "/decrypt":
    post:
      summary: "Decrypt data"
      operationId: "postV2Decrypt"
      x-mint: "/api/v2/decrypt"
      responses:
        '200':
          description: "Decrypted data"
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        '400':
          description: "Unable to process encrypted data"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                cannotDecrypt:
                  summary: "You are not authorized to decrypt this content"
                  value:
                    message: "You are not authorized to decrypt this content"
                forbidden:
                  $ref: '#/components/examples/forbidden'
        '404':
          description: "Encryption metadata not found"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: "Decryption failed"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Qanapi-Authorization
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Unauthorized - Invalid API Key
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            unauthorized:
              $ref: '#/components/examples/unauthorized'
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            forbidden:
              $ref: '#/components/examples/forbidden'
  examples:
    unauthorized:
      value:
        message: "Unauthenticated."
    forbidden:
      value:
        message: "This action is unauthorized."
security:
  - ApiKey: [ ]
    BearerAuth: [ ]
